# Generated by Django 6.0.6 on 2026-06-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('short_bio', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('github', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedln', models.URLField()),
                ('instagram', models.URLField()),
                ('resume', models.FileField(upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
