# Generated by Django 6.0.6 on 2026-07-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_profile_skill_alter_profile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
    ]
