# Generated by Django 6.0.6 on 2026-07-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_remove_profile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='static/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='static/resume/'),
        ),
    ]
