# Generated by Django 6.0.6 on 2026-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_alter_profile_profile_image_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='media/static/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='media/static/resume/'),
        ),
    ]
